root = "."
tmp_dir = "tmp"

[build]
  # Just plain old shell command. You could use `make` as well.
  cmd = "go build -o main cmd/web/main.go"
  # Binary file yields from `cmd`.
  bin = "main"
  # Add additional arguments when running binary (bin/full_bin). Will run './tmp/main hello world'.
  args_bin = []
  # Watch these filename extensions.
  include_ext = ["go"]
  # Ignore these filename extensions or directories.
  exclude_dir = ["vendor"]
  # This log file places in your tmp_dir.
  log = "air.log"
  # Stop running old binary when build errors occur.
  stop_on_error = true
  # Send Interrupt signal before killing process (windows does not support this feature)
  send_interrupt = false

[log]
  level = "debug"